'use strict';

module.exports = Object.freeze({
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  CORS_ORIGIN_DENIED: 'CORS_ORIGIN_DENIED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  DEVICE_DISABLED: 'DEVICE_DISABLED',
  MODBUS_TIMEOUT: 'MODBUS_TIMEOUT',
  MODBUS_CONNECTION_ERROR: 'MODBUS_CONNECTION_ERROR',
  MODBUS_EXCEPTION: 'MODBUS_EXCEPTION',
  MODBUS_OPERATION_ERROR: 'MODBUS_OPERATION_ERROR',
  MODBUS_POOL_EXHAUSTED: 'MODBUS_POOL_EXHAUSTED',
  POLLING_DISABLED: 'POLLING_DISABLED',
  POLL_IN_PROGRESS: 'POLL_IN_PROGRESS',
  REGISTER_PROFILE_UNAVAILABLE: 'REGISTER_PROFILE_UNAVAILABLE',
  REGISTER_DECODE_ERROR: 'REGISTER_DECODE_ERROR',
  MODBUS_GATEWAY_ERROR: 'MODBUS_GATEWAY_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});
